HMD_COUNTRIES = {
    "AUS": "Australia",
    "AUT": "Austria",
    "BEL": "Belgium",
    "BGR": "Bulgaria",
    "CAN": "Canada",
    "CHE": "Switzerland",
    "CZE": "Czechia",
    "DNK": "Denmark",
    "ESP": "Spain",
    "FIN": "Finland",
    "FRATNP": "France",
    "GBR_NIR": "Northern Ireland",
    "GBR_SCO": "Scotland",
    "GBRTENW": "England & Wales",
    "HUN": "Hungary",
    "IRL": "Ireland",
    "ISL": "Iceland",
    "JPN": "Japan",
    "NLD": "Netherlands",
    "NOR": "Norway",
    "SVK": "Slovakia",
    "SWE": "Sweden",
    "USA": "USA"
}